walls:
  - name: "table"
    x_thickness: 2
    y_thickness: 2.25
    z_thickness: 0.05
    qx: 0
    qy: 0
    qz: 0.3826834323650898
    qw: 0.9238795325112867
    x: 0.87
    y: -0.87
    z: -0.34
    frame_id: base_link
  - name: "staubli"
    x_thickness: .6
    y_thickness: .05
    z_thickness: 4
    qx: 0
    qy: 0
    qz: 0.3826834323650898
    qw: 0.9238795325112867
    x: 0.75
    y: -0.75
    z: -0.35
    frame_id: base_link
  - name: "table2"
    x_thickness: 2
    y_thickness: 2.25
    z_thickness: 0.05
    qx: 0
    qy: 0
    qz: 0.3826834323650898
    qw: 0.9238795325112867
    x: -0.87
    y: 0.87
    z: -0.35
    frame_id: base_link
  - name: "table3"
    x_thickness: 2.25
    y_thickness: 2
    z_thickness: 0.05
    qx: 0
    qy: 0
    qz: 0.3826834323650898
    qw: 0.9238795325112867
    x: 0.87
    y: 0.87
    z: -0.35
    frame_id: base_link
  - name: "table4"
    x_thickness: 2.25
    y_thickness: 2
    z_thickness: 0.05
    qx: 0
    qy: 0
    qz: 0.3826834323650898
    qw: 0.9238795325112867
    x: -0.87
    y: -0.87
    z: -0.35
    frame_id: base_link
  - name: "camera"
    x_thickness: 0.6
    y_thickness: 0.35
    z_thickness: 0.4
    qx: 0
    qy: 0
    qz: 0.3826834323650898
    qw: 0.9238795325112867
    x: 0.409
    y: -0.342
    z: 0.775
    frame_id: base_link